---
defaults: &defaults
  docker:
    - image: hseeberger/scala-sbt:11.0.1_2.12.8_1.2.7

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "project/build.properties" }}

      - run:
          name: "Compile"
          command: sbt compile

      - run:
          name: "Unit Tests"
          command: sbt test

      - run:
          name: "Package"
          command: |
            set -x
            export SEMVER=$(echo "$CIRCLE_TAG" | grep "^v.*$" | cut -c 2-)
            export VERSION=$(echo $CIRCLE_SHA1 | tr / _)-SNAPSHOT
            [ -n "$SEMVER" ] && export VERSION=$(echo $SEMVER | tr / _)
            sbt "set ThisBuild / version := \"$VERSION\"" package

      - save_cache:
          key: sbt-cache-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "project/build.properties" }}
          root: ~/
          paths:
            - .ivy2/cache
            - .sbt
            - .m2
      - persist_to_workspace:
          root: ~/
          paths:
            - .sbt
            - .ivy2/cache
            - .m2
            - project

  publish_snapshot:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Publish Snapshot"
          command: |
            export SEMVER=$(echo "$CIRCLE_TAG" | grep "^v.*$" | cut -c 2-)
            export VERSION=$(echo $CIRCLE_SHA1 | tr / _)-SNAPSHOT
            [ -n "$SEMVER" ] && export VERSION=$(echo $SEMVER | tr / _)
            sbt "set ThisBuild / version := \"$VERSION\"" publish

  publish_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Publish Release"
          command: |
            export SEMVER=$(echo "$CIRCLE_TAG" | grep "^v.*$" | cut -c 2-)
            export VERSION=$(echo $CIRCLE_SHA1 | tr / _)-SNAPSHOT
            [ -n "$SEMVER" ] && export VERSION=$(echo $SEMVER | tr / _)
            sbt "set ThisBuild / version := \"$VERSION\"" publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish_snapshot:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish_release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
